name: ${{values.app_name}}-cicd

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ '${{ secrets.DOCKERHUB_USERNAME }}' }} 
          password: ${{ '${{ secrets.DOCKERHUB_TOKEN }}' }}
    
      - 
        name: Generate Short Github Commit id
        shell: bash
        run: |
          echo "COMMIT_ID=${GITHUB_SHA::6}" >> ${GITHUB_ENV} 

      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: aumthakkar/${{values.app_name}}:${{ '${{env.COMMIT_ID}}' }}

    outputs:
      commit_id: ${{ '${{env.COMMIT_ID}}' }}

  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - 
        name: Clone your github repo
        uses: actions/checkout@v5

      - 
        name: Modify charts values file
        shell: bash
        run: |
          echo "${{ '${{needs.ci.outputs.commit_id}}' }}"
          sudo apt update && sudo apt install python3-pip -y
          pip3 install yq --break-system-packages
          yq -Yi '.image.tag = "${{ '${{needs.ci.outputs.commit_id}}' }}"' charts/${{values.app_name}}//values-${{values.app_env}}.yaml

      - 
        name: Commit changes back to your Github repo
        uses: EndBug/add-and-commit@v9
        with:
          message: "Updated Helm values.yaml file with commit ${{ '${{needs.ci.outputs.commit_id}}' }} "

      - 
        name: Install and configure ArgoCD
        shell: bash
        run: |
          curl -ksSL -o /tmp/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x /tmp/argocd
          sudo mv /tmp/argocd /usr/local/bin/argocd

      -
        name: ArgoCD login
        shell: bash
        run: |
          argocd login argocd-server.argocd \
          --insecure \
          --grpc-web \
          --username admin \
          --password ${{ '${{secrets.ARGOCD_PASSWORD}}' }}

          argocd app sync ${{values.app_name}}


          
    
    